const icons={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',transactions:'<path d="M4 8h16m-4-4 4 4-4 4M20 16H4m4-4-4 4 4 4"/>',invoice:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6m-6 4h6"/>',budget:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 9h18m-6 4h6m-4 0v3"/>',chart:'<path d="M4 3v17h17M8 15v-4m5 4V7m5 8V4"/>',settings:'<path d="m9 3-1 3-3 1-1 3 2 2-1 3 2 2 3-1 2 2 3-1 1-3 3-1 1-3-2-2 1-3-3-1-2 1-2-2Z"/><circle cx="12" cy="11" r="3"/>',bell:'<path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3Zm5 3h4"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',upload:'<path d="M12 16V4m-4 4 4-4 4 4M4 15v6h16v-6"/>',wallet:'<rect x="3" y="6" width="18" height="14" rx="3"/><path d="M3 7V5l14-2v3m-2 7h6m-4 0v3"/>',up:'<path d="M5 17 18 4M7 4h11v11"/>',down:'<path d="M5 7 18 20M7 20h11V9"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.invoice}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const money=n=>(state.currency==='IRT'?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n)+' IRT':new Intl.NumberFormat('en-US',{style:'currency',currency:state.currency||'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=new Date();const localDate=(date=now)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const monthDate=(day,offset=0)=>localDate(new Date(now.getFullYear(),now.getMonth()+offset,day));
const seed=()=>({transactions:[{id:'t1',name:'Website redesign',company:'Linear Studio',type:'income',category:'Client payments',amount:4250,date:monthDate(15)},{id:'t2',name:'Figma subscription',company:'Figma',type:'expense',category:'Software',amount:144,date:monthDate(14)},{id:'t3',name:'Brand identity project',company:'Notion Labs',type:'income',category:'Client payments',amount:2800,date:monthDate(13)},{id:'t4',name:'Workspace rent',company:'The Working Capitol',type:'expense',category:'Office',amount:1250,date:monthDate(12)},{id:'t5',name:'Google Workspace',company:'Google',type:'expense',category:'Software',amount:72,date:monthDate(11)},{id:'t6',name:'Social media campaign',company:'Meta',type:'expense',category:'Marketing',amount:680,date:monthDate(10)},{id:'t7',name:'Design consulting',company:'Acme Inc.',type:'income',category:'Consulting',amount:5400,date:monthDate(8)},{id:'t8',name:'Team lunch',company:'Little Collins',type:'expense',category:'Other',amount:184,date:monthDate(6)},{id:'t9',name:'Adobe Creative Cloud',company:'Adobe',type:'expense',category:'Software',amount:89,date:monthDate(4)},{id:'t10',name:'Office equipment',company:'Office Supply Co.',type:'expense',category:'Office',amount:780,date:monthDate(3)},...Array.from({length:5},(_,i)=>[{id:`hi${i}`,name:'Client projects',company:'Monthly projects',type:'income',category:'Client payments',amount:[8400,10100,9200,11500,10800][i],date:monthDate(5,i-5)},{id:`he${i}`,name:'Business expenses',company:'Monthly expenses',type:'expense',category:'Other',amount:[4200,5100,3900,5400,4600][i],date:monthDate(5,i-5)}]).flat()],invoices:[{id:'INV-001',client:'Linear Studio',description:'Website development',amount:4250,date:monthDate(22),status:'pending'},{id:'INV-002',client:'Notion Labs',description:'Design retainer',amount:1800,date:monthDate(25),status:'pending'},{id:'INV-003',client:'Layers Agency',description:'Brand consultation',amount:1200,date:monthDate(28),status:'pending'}],budgets:[{name:'Software',limit:500},{name:'Marketing',limit:1000},{name:'Office',limit:2500},{name:'Other',limit:500}],openingBalance:12500});
let state={transactions:[],invoices:[],budgets:[],openingBalance:0,currency:'USD'},account=null;
let page='dashboard',query='',typeFilter='all',chartPeriod=6,formMode='transaction';
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
const current=()=>state.transactions.filter(t=>t.date.slice(0,7)===localDate().slice(0,7));
const total=(ts,type)=>ts.filter(t=>t.type===type).reduce((sum,t)=>sum+t.amount,0);
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});
function heading(title,sub,action='transaction'){return `<div class="page-heading"><div><div class="eyebrow">YOUR BUSINESS, AT A GLANCE</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="heading-actions"><button class="button" data-action="export">${icon('upload')} Export</button><button class="button import-button" data-action="import">${icon('download')} Import</button><button class="button primary" data-action="${action}"><span class="plus">+</span> ${action==='invoice'?'New invoice':action==='budget'?'Set budget':'Add transaction'}</button></div></div>`}
function stats(){const ts=current(),income=total(ts,'income'),expense=total(ts,'expense'),balance=state.openingBalance+total(state.transactions,'income')-total(state.transactions,'expense'),pending=state.invoices.filter(i=>i.status==='pending');return `<div class="stats">${[['Total balance',balance,'wallet','Available funds','Across all transactions'],['Income',income,'up','This month',`${ts.filter(t=>t.type==='income').length} payments received`],['Expenses',expense,'down','This month',`${ts.filter(t=>t.type==='expense').length} payments made`],['Unpaid invoices',pending.reduce((s,i)=>s+i.amount,0),'invoice',`${pending.length} pending`,'Awaiting payment']].map(([label,value,ic,badge,note],i)=>`<div class="stat"><div class="stat-label">${label}<span class="stat-icon">${icon(ic)}</span></div><div class="stat-value">${money(value)}</div><div class="stat-note"><span class="badge ${i===3?'orange':''}">${badge}</span>${note}</div></div>`).join('')}</div>`}
function chart(){let months=Array.from({length:chartPeriod},(_,i)=>new Date(now.getFullYear(),now.getMonth()-chartPeriod+1+i,1));let values=months.map(d=>{let rows=state.transactions.filter(t=>t.date.slice(0,7)===localDate(d).slice(0,7));return [total(rows,'income'),total(rows,'expense')]});let max=Math.max(1000,...values.flat());max=Math.ceil(max/4000)*4000;let grid=Array.from({length:5},(_,i)=>{const y=20+i*37;return `<line x1="48" x2="565" y1="${y}" y2="${y}" stroke="#eeedf4" stroke-dasharray="3 4"/><text x="0" y="${y+3}">${(max*(4-i)/4/1000).toFixed(0)}k</text>`}).join('');let bars=values.map((v,i)=>{let x=64+i*(492/chartPeriod);return `<rect x="${x}" y="${168-v[0]/max*148}" width="${chartPeriod===6?22:38}" height="${v[0]/max*148}" rx="4" fill="#9982df"/><rect x="${x+(chartPeriod===6?27:44)}" y="${168-v[1]/max*148}" width="${chartPeriod===6?22:38}" height="${v[1]/max*148}" rx="4" fill="#ded6f1"/><text x="${x+23}" y="193" text-anchor="middle">${months[i].toLocaleDateString('en-US',{month:'short'})}</text>`}).join('');return `<section class="card"><div class="card-head"><div><h2>Cash flow</h2><div class="card-subtitle">A little perspective on your money in and out.</div></div><select class="small-select" id="chart-period" aria-label="Cash flow period"><option value="6" ${chartPeriod===6?'selected':''}>Last 6 months</option><option value="3" ${chartPeriod===3?'selected':''}>Last 3 months</option></select></div><div class="chart-legend"><span><i class="legend-dot"></i>Income</span><span><i class="legend-dot light"></i>Expenses</span><span class="chart-note">In ${esc(state.currency||'USD')}</span></div><svg class="cash-chart" role="img" aria-label="Monthly income and expenses. ${months.map((d,i)=>`${d.toLocaleDateString('en-US',{month:'long'})}: income ${money(values[i][0])}, expenses ${money(values[i][1])}`).join('; ')}" viewBox="0 0 580 205">${grid}${bars}</svg></section>`}
function spending(){let cats=['Office','Marketing','Software','Other'],colors=['#8d76d5','#b49cde','#cfc0e8','#e9e3f3'];let vals=cats.map(c=>current().filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0)),sum=vals.reduce((a,b)=>a+b,0),pos=0;let gradient=vals.map((v,i)=>{let start=pos;pos+=sum?v/sum*100:0;return `${colors[i]} ${start}% ${pos}%`}).join(',');return `<section class="card"><div class="card-head"><div><h2>Spending breakdown</h2><div class="card-subtitle">Where your money is going.</div></div><span class="small-select">This month</span></div><div class="spend-content"><div class="donut" style="background:${sum?`conic-gradient(${gradient})`:'#f1eef8'}"><div class="donut-center"><small>Total expenses</small><strong>${money(sum)}</strong></div></div></div><div class="spend-legend">${cats.map((c,i)=>`<div><i class="legend-dot" style="background:${colors[i]}"></i>${c}<strong>${sum?Math.round(vals[i]/sum*100):0}%</strong></div>`).join('')}</div></section>`}
function transactionRows(rows,full=false){return rows.map(t=>`<tr><td><div class="transaction-name"><div class="merchant ${t.type==='income'?'green':t.category==='Office'?'blue':''}">${t.type==='income'?'↙':esc(t.company.charAt(0))}</div><span class="transaction-description" dir="auto">${esc(t.name)}${full?'':`<small>${esc(t.company)}</small>`}</span></div></td>${full?`<td dir="auto">${esc(t.company)}</td>`:''}<td class="category-col"><span class="category">${esc(t.category)}</span></td><td>${full?esc(t.date):dateLabel(t.date)}${full?`<small class="transaction-time">${esc(t.time||'—')}</small>`:''}</td><td class="amount ${t.type}">${t.type==='income'?'+':'−'}${money(t.amount)}</td>${full?`<td dir="auto" class="reference-code">${esc(t.referenceCode||'—')}</td><td dir="auto">${esc(t.bank||'—')}</td><td><button class="delete-button" data-delete="${esc(t.id)}" aria-label="Delete ${esc(t.name)}">✕</button></td>`:''}</tr>`).join('')}
function transactionTable(rows,full=false){return `<div class="table-wrap transactions-table"><table><thead><tr><th>${full?'Description / reason':'Transaction'}</th>${full?'<th>Recipient</th>':''}<th class="category-col">Category</th><th>${full?'Date / time':'Date'}</th><th class="amount">Price / amount</th>${full?'<th>Tracking / backup code</th><th>Originating bank</th><th></th>':''}</tr></thead><tbody>${transactionRows(rows,full)||`<tr><td colspan="${full?8:4}" class="empty">No transactions found. Import a CSV or add one to get started.</td></tr>`}</tbody></table></div>`}
function budgetRow(b){let spent=current().filter(t=>t.type==='expense'&&t.category===b.name).reduce((s,t)=>s+t.amount,0),pct=Math.round(spent/b.limit*100);return `<div class="budget-row"><div class="budget-top"><span>${esc(b.name)}</span><span><strong>${money(spent)}</strong> / ${money(b.limit)}</span></div><div class="progress"><div style="width:${Math.min(pct,100)}%;background:${pct>100?'#d38a84':pct>80?'#d7b489':'#aa94df'}"></div></div><div class="budget-bottom"><span>${pct}% used</span><span>${money(Math.abs(b.limit-spent))} ${spent>b.limit?'over budget':'left'}</span></div></div>`}
function dashboard(){return heading(`Good morning, ${esc(account.name)} ☀`,'Here’s what’s happening with your business today.')+`<div class="welcome-strip"><span class="spark">✧</span><span><strong>Your books, a little brighter.</strong> Keep everything in view and make your next move with confidence.</span><button class="text-link" data-page="reports">View insights ↗</button></div>`+stats()+`<div class="analytics">${chart()}${spending()}</div><div class="lower-grid"><section class="card"><div class="card-head"><div><h2>Recent transactions</h2><div class="card-subtitle">The latest activity across your business.</div></div><button class="text-link" data-page="transactions">View all ↗</button></div>${transactionTable([...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}<div class="table-footer"><span>Showing ${Math.min(5,state.transactions.length)} of ${state.transactions.length} transactions</span><span>Updated just now</span></div></section><section class="card"><div class="card-head"><div><h2>Monthly budgets</h2><div class="card-subtitle">A plan for every dollar.</div></div><button class="text-link" data-page="budgets">Manage ↗</button></div><div class="budget-list">${state.budgets.slice(0,3).map(budgetRow).join('')}</div><div class="budget-callout"><span>✧</span>Small check-ins make a big difference. Keep an eye on your monthly spending.</div></section></div>`}
function filteredTransactions(){return [...state.transactions].filter(t=>(typeFilter==='all'||t.type===typeFilter)&&`${t.name} ${t.company} ${t.category} ${t.referenceCode||''} ${t.bank||''} ${t.date} ${t.time||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||(b.time||'').localeCompare(a.time||''))}
function transactions(){return heading('Transactions','Every payment, every purchase. All accounted for.')+`<section class="card"><div class="toolbar"><input class="search" id="search" placeholder="Search transactions…" aria-label="Search transactions" value="${esc(query)}"><select class="small-select" id="type-filter" aria-label="Transaction type">${['all','income','expense'].map(v=>`<option value="${v}" ${v===typeFilter?'selected':''}>${v==='all'?'All transactions':v==='income'?'Income':'Expenses'}</option>`).join('')}</select></div><div id="transaction-results">${transactionTable(filteredTransactions(),true)}</div></section>`}
function invoices(){return heading('Invoices','Less chasing. More time for the work you love.','invoice')+`<section class="card"><div class="card-head"><h2>Your invoices</h2><span class="card-subtitle">Mark as paid to record income automatically</span></div><div class="table-wrap transactions-table"><table><thead><tr><th>Client / invoice</th><th>Due date</th><th>Status</th><th class="amount">Amount</th><th></th></tr></thead><tbody>${state.invoices.map(i=>`<tr><td><div class="transaction-name"><span>${esc(i.client)}<small>${esc(i.id)} · ${esc(i.description)}</small></span></div></td><td>${dateLabel(i.date)}, ${i.date.slice(0,4)}</td><td><span class="status ${i.status}">${i.status==='paid'?'Paid':'Pending'}</span></td><td class="amount">${money(i.amount)}</td><td>${i.status==='pending'?`<button class="button" data-pay="${esc(i.id)}">Mark paid</button>`:'✓ Recorded'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No invoices yet.</td></tr>'}</tbody></table></div></section>`}
function budgets(){return heading('Monthly budgets','Give your spending a little direction.','budget')+`<div class="budget-page">${state.budgets.map(b=>`<section class="card">${budgetRow(b)}<button class="text-link" style="margin-top:20px" data-budget="${esc(b.name)}">Edit budget ↗</button></section>`).join('')}</div>`}
function reports(){const ts=current(),income=total(ts,'income'),expense=total(ts,'expense');return heading('Financial reports','A clearer picture of how your business is doing.')+stats()+`<div class="analytics">${chart()}${spending()}</div><section class="card"><div class="card-head"><h2>Your monthly snapshot</h2><span class="status">${now.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</span></div><div class="report-summary">You earned <strong>${money(income)}</strong> and spent <strong>${money(expense)}</strong> this month.<br>Your net cash flow is <strong>${money(income-expense)}</strong>${income?`, with a net margin of <strong>${((income-expense)/income*100).toFixed(1)}%</strong>`:''}.<br>${state.budgets.filter(b=>current().filter(t=>t.type==='expense'&&t.category===b.name).reduce((s,t)=>s+t.amount,0)>b.limit).length} categories are over budget. Export your transactions for a closer look.</div></section>`}
function settings(){return workspaceSettings()}
function render(){if(!account)return;document.getElementById('page').innerHTML=({dashboard,transactions,invoices,budgets,reports,settings}[page]||dashboard)();document.getElementById('breadcrumb').textContent=page==='dashboard'?'Overview':page[0].toUpperCase()+page.slice(1);document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('invoice-count').textContent=state.invoices.filter(i=>i.status==='pending').length;const alert=document.getElementById('save-alert');alert.hidden=!saveFailure;if(saveFailure)alert.querySelector('span').textContent=saveFailure;if(page==='settings'&&account.role==='admin')loadUsers()}
function go(next){page=['dashboard','transactions','invoices','budgets','reports','settings'].includes(next)?next:'dashboard';location.hash=page;render()}
function field(label,name,type='text',value='',extra=''){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" required ${extra}></label>`}
function openForm(mode,budgetName){formMode=mode;const titles={transaction:'New transaction',invoice:'New invoice',budget:'Set monthly budget'};document.getElementById('dialog-title').textContent=titles[mode];const categories=['Software','Marketing','Office','Other','Client payments','Consulting'];let html='';if(mode==='transaction')html=`<div class="form-grid"><label class="field">Type<select name="type"><option value="expense">Expense</option><option value="income">Income</option></select></label>${field('Amount ('+(state.currency||'USD')+')','amount','number','','min="0.01" max="999999999" step="0.01"')}</div>${field('Description','name','text','','maxlength="100"')}${field('Recipient / business','company','text','','maxlength="80"')}<div class="form-grid"><label class="field">Category<select name="category">${categories.slice(0,4).map(c=>`<option>${c}</option>`).join('')}</select></label>${field('Date','date','date',localDate())}</div>`;if(mode==='invoice')html=field('Client name','client','text','','maxlength="80"')+field('Description','description','text','','maxlength="100"')+`<div class="form-grid">${field('Amount ('+(state.currency||'USD')+')','amount','number','','min="0.01" max="999999999" step="0.01"')}${field('Due date','date','date',localDate())}</div>`;if(mode==='budget')html=`<label class="field">Category<select name="name">${categories.slice(0,4).map(c=>`<option ${c===budgetName?'selected':''}>${c}</option>`).join('')}</select></label>${field('Monthly limit ('+(state.currency||'USD')+')','limit','number',state.budgets.find(b=>b.name===(budgetName||'Software'))?.limit||500,'min="0.01" max="999999999" step="0.01"')}`;if(mode==='transaction')html+=`<div class="form-grid"><label class="field">Time (optional)<input name="time" type="time" step="1"></label><label class="field">Tracking / backup code (optional)<input name="referenceCode" type="text" maxlength="200"></label></div><label class="field">Originating bank (optional)<input name="bank" type="text" maxlength="150"></label>`;document.getElementById('form-fields').innerHTML=html;document.getElementById('entry-dialog').showModal()}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value){return '"'+String(value??'').replace(/^(\s*)([=+\-@\t\r])/u,"'$1$2").replace(/"/g,'""')+'"'}
function exportCSV(){let rows=[['Date','Time','Description','Recipient','Type','Category','Price','Tracking code','Originating bank','Currency'],...(page==='transactions'?filteredTransactions():state.transactions).map(t=>[t.date,t.time||'',t.name,t.company,t.type,t.category,t.amount,t.referenceCode||'',t.bank||'',state.currency||'USD'])];download('\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),`ledger-transactions-${localDate()}.csv`,'text/csv;charset=utf-8');toast('Your transaction export is ready')}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button,a');if(!b||!account||saving)return;
 try {
  if(b.dataset.page)go(b.dataset.page);
  if(b.dataset.action){const a=b.dataset.action;
   if(['transaction','invoice','budget'].includes(a))openForm(a);
   if(a==='export')exportCSV();
   if(a==='backup'){download(JSON.stringify(state,null,2),`ledger-backup-${localDate()}.json`,'application/json');toast('Backup downloaded')}
   if(a==='clear'&&confirm('Clear all transactions, invoices, budgets, and the opening balance from YOUR account? Download a backup first.')){
    await commitState({...blankWorkspace(),currency:state.currency||'USD'});render();toast('Your books are ready for a fresh start');
   }
  }
  if(b.dataset.budget)openForm('budget',b.dataset.budget);
  if(b.dataset.delete&&confirm('Delete this transaction?')){
   await commitState({...state,transactions:state.transactions.filter(t=>t.id!==b.dataset.delete)});render();toast('Transaction deleted');
  }
  if(b.dataset.pay){const next=structuredClone(state),inv=next.invoices.find(i=>i.id===b.dataset.pay);
   if(inv&&inv.status==='pending'){inv.status='paid';next.transactions.push({id:crypto.randomUUID(),name:inv.description,company:inv.client,type:'income',category:'Client payments',amount:inv.amount,date:localDate()});await commitState(next);render();toast('Invoice paid. Income added to your books.')}
  }
 }catch(error){toast(error.message)}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;document.getElementById('transaction-results').innerHTML=transactionTable(filteredTransactions(),true)}});
document.addEventListener('change',e=>{if(e.target.id==='type-filter'){typeFilter=e.target.value;document.getElementById('transaction-results').innerHTML=transactionTable(filteredTransactions(),true)}if(e.target.id==='chart-period'){chartPeriod=Number(e.target.value);render()}if(e.target.name==='type'&&formMode==='transaction'){document.querySelector('[name="category"]').innerHTML=(e.target.value==='income'?['Client payments','Consulting']:['Software','Marketing','Office','Other']).map(c=>`<option>${c}</option>`).join('')}if(e.target.name==='name'&&formMode==='budget'){document.querySelector('[name="limit"]').value=state.budgets.find(b=>b.name===e.target.value)?.limit||500}});
document.getElementById('entry-form').addEventListener('submit',async e=>{
 e.preventDefault();if(!account||saving)return;
 const data=Object.fromEntries(new FormData(e.target));for(const key of Object.keys(data))data[key]=data[key].trim();
 if(Object.entries(data).some(([k,v])=>!v&&!['time','referenceCode','bank'].includes(k))){toast('Please complete every field');return}
 const next=structuredClone(state);
 if(formMode==='transaction')next.transactions.push({...data,amount:Number(data.amount),id:crypto.randomUUID()});
 else if(formMode==='invoice')next.invoices.push({...data,amount:Number(data.amount),status:'pending',id:`INV-${crypto.randomUUID().slice(0,8).toUpperCase()}`});
 else {const b=next.budgets.find(b=>b.name===data.name);if(b)b.limit=Number(data.limit);else next.budgets.push({name:data.name,limit:Number(data.limit)})}
 try{await commitState(next);document.getElementById('entry-dialog').close();render();toast(formMode==='budget'?'Monthly budget updated':'Entry saved to your account.')}
 catch(error){toast(error.message)}
});
['close-dialog','cancel-dialog'].forEach(id=>document.getElementById(id).onclick=()=>document.getElementById('entry-dialog').close());
document.getElementById('notifications').onclick=()=>toast(`${state.invoices.filter(i=>i.status==='pending').length} invoices are awaiting payment. View them in Invoices.`);
document.getElementById('workspace').onclick=()=>go('settings');
document.getElementById('today').textContent=now.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'dashboard';if(!['dashboard','transactions','invoices','budgets','reports','settings'].includes(page))page='dashboard';render()});
page=location.hash.slice(1)||'dashboard';if(!['dashboard','transactions','invoices','budgets','reports','settings'].includes(page))page='dashboard';
