const assert = require('node:assert/strict');
const CSV = require('./csv.js');
const header = 'Price,Recipient,Date,Time,Description,Tracking code,Originating bank,Type,Currency';
const row = '"1,250.50",Example recipient,2026-09-16,14:35:20,"Payment, invoice 4",0000123456789,Example Bank,expense,USD';
const options = { direction: 'expense', currency: 'USD' };
function validate(text, settings = options, existing = []) {
  const parsed = CSV.detectCSV(text);
  return CSV.validate(parsed, CSV.autoMap(parsed.headers), settings, existing);
}
const basic = validate('\uFEFF' + header + '\r\n' + row + '\r\n');
assert.equal(basic.ready.length, 1);
assert.equal(basic.ready[0].amount, 1250.5);
assert.equal(basic.ready[0].referenceCode, '0000123456789');
assert.equal(basic.ready[0].bank, 'Example Bank');
assert.equal(basic.ready[0].time, '14:35:20');
assert.equal(basic.ready[0].source.values[4], 'Payment, invoice 4');
assert.equal(validate(header + '\n' + row + '\n' + row).duplicates, 1);
assert.equal(validate(header + '\n' + row, options, basic.ready).duplicates, 1);
assert.equal(validate(header + '\n' + row.replace('1,250.50', '1,260.50'), options, basic.ready).invalid, 1);
const multi = CSV.parseCSV('A,B\r\n"line 1\r\nline 2","He said ""yes"""\r\nC,D');
assert.equal(multi.rows[0].cells[1], 'He said "yes"');
assert.equal(multi.rows[1].line, 4);
assert.throws(() => CSV.parseCSV('A,B\n"not closed,4'), /not closed/);
assert.throws(() => CSV.parseCSV('A,B\n"closed"oops,4'), /unexpected text/);
assert.throws(() => CSV.parseCSV('A,B\na"b,4'), /unquoted/);
assert.equal(CSV.detectCSV('A;B\n"1,250";x').delimiter, ';');
assert.equal(CSV.detectCSV('A\tB\n1\tx').delimiter, '\t');
assert.equal(validate(header + '\n' + row + ',extra').invalid, 1);
assert.equal(validate(header + '\n' + row.replace('14:35:20,', '')).invalid, 1);
assert.equal(CSV.parseAmount('۱٬۲۳۴٫۵۶').amount, 1234.56);
assert.equal(CSV.parseAmount('١٢٣٤٫٥٦').amount, 1234.56);
assert.equal(CSV.parseAmount('1.234,56', 'comma').amount, 1234.56);
assert.equal(CSV.parseAmount('1 234.56').amount, 1234.56);
assert.equal(CSV.parseAmount('(1,234.56)').negative, true);
assert.equal(CSV.parseAmount('−20').negative, true);
for (const value of ['12,34.56', '1.234', '1,23', '$100', '12abc', '1e3', 'Infinity', '0', '', '(-10)', '1 2', '1000000000000']) assert.throws(() => CSV.parseAmount(value), undefined, value);
assert.equal(CSV.parseDate('16/09/2026', 'dmy').date, '2026-09-16');
assert.equal(CSV.parseDate('09/16/2026', 'mdy').date, '2026-09-16');
assert.equal(CSV.parseDate('2024-02-29').date, '2024-02-29');
assert.equal(CSV.parseDate('۱۴۰۵/۰۶/۲۵', 'ymd', 'jalali').date, '2026-09-16');
assert.equal(CSV.parseDate('1403/01/01', 'ymd', 'jalali').date, '2024-03-20');
assert.throws(() => CSV.parseDate('1404/12/30', 'ymd', 'jalali'), /Invalid Jalali/);
for (const value of ['2025-02-29', '2026-13-01', '2026-00-01', '2026-09-31', '2026-09/16', '26-09-16', '1405/06/25']) assert.throws(() => CSV.parseDate(value), undefined, value);
assert.equal(CSV.parseTime('12:05 AM'), '00:05:00');
assert.equal(CSV.parseTime('12:05 PM'), '12:05:00');
assert.equal(CSV.parseTime('۲۳:۰۹:۴۵'), '23:09:45');
for (const value of ['24:00', '12:60', '12:05:60', '0:30 pm', '13:30 pm', '12:00Z']) assert.throws(() => CSV.parseTime(value), undefined, value);
assert.equal(CSV.parseDate('2026-09-16 2:35 PM').embeddedTime, '14:35:00');
assert.equal(validate(header + '\n' + row.replace('2026-09-16', '2026-09-16 01:00:00')).invalid, 1);
assert.equal(validate(header + '\n' + row.replace('expense', 'unknown')).invalid, 1);
assert.equal(validate(header + '\n' + row.replace('1,250.50', '-1,250.50').replace('expense', 'income')).invalid, 1);
assert.equal(validate(header + '\n' + row.replace('USD', 'IRR')).invalid, 1);
const noType = 'Price,Recipient,Date,Description,Bank\n100,Someone,2026-09-16,Payment,My bank';
assert.equal(validate(noType, { direction: '' }).invalid, 1);
assert.equal(validate(noType, { direction: 'signed' }).ready[0].type, 'income');
assert.equal(validate(noType.replace('\n100,', '\n-100,'), { direction: 'signed' }).ready[0].type, 'expense');
assert.equal(validate(noType).rows[0].warnings.length, 2);
const persian = 'مبلغ;گیرنده;تاریخ;ساعت;بابت;کد پیگیری;بانک مبدا;نوع;واحد پول\n۱۲۵۰۰۰;علی رضایی;۱۴۰۵/۰۶/۲۵;۱۴:۳۵:۲۰;پرداخت فاکتور;۰۰۰۱۲۳;بانک ملت;برداشت;ریال';
const iran = validate(persian, { calendar: 'jalali', currency: 'IRR' });
assert.equal(iran.ready.length, 1);
assert.equal(iran.ready[0].company, 'علی رضایی');
assert.equal(iran.ready[0].referenceCode, '۰۰۰۱۲۳');
assert.equal(iran.ready[0].amount, 125000);
assert.equal(iran.ready[0].date, '2026-09-16');
const unknown = CSV.parseCSV('One,Two,Three\nx,y,z');
assert.ok(CSV.validate(unknown, CSV.autoMap(unknown.headers)).errors.length);
const parsed = CSV.detectCSV(header + '\n' + row), mapping = CSV.autoMap(parsed.headers);
assert.ok(CSV.validate(parsed, { ...mapping, name: mapping.company }).errors.some(e => e.includes('only be mapped once')));
assert.equal(CSV.autoMap(['Price', 'Amount']).amount, -1, 'ambiguous columns require manual mapping');
assert.equal(validate(header + '\n' + row.replace('Example recipient', '<img src=x onerror=alert(1)>')).ready[0].company, '<img src=x onerror=alert(1)>', 'raw text retained for escaped rendering');
console.log('Passed: CSV quoting, separators, BOM, multiline records, all seven fields, leading zeros, Persian headers/digits, amount/date/time validation, Jalali conversion, direction/currency rules, and duplicates/conflicts.');
